// <auto-generated />
using Labs.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labs.API.Migrations
{
    [DbContext(typeof(LabsDBContext))]
    [Migration("20241120145021_seed")]
    partial class seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Labs.API.Models.Produto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Marca = "CAT",
                            Nome = "Roda de Carro",
                            Quantidade = 15
                        },
                        new
                        {
                            Id = 2L,
                            Marca = "CAT",
                            Nome = "Roda de Moto",
                            Quantidade = 190
                        },
                        new
                        {
                            Id = 3L,
                            Marca = "CAT",
                            Nome = "Roda de Bicicleta",
                            Quantidade = 130
                        },
                        new
                        {
                            Id = 4L,
                            Marca = "Mattel",
                            Nome = "Carro de controle remoto",
                            Quantidade = 9
                        },
                        new
                        {
                            Id = 5L,
                            Marca = "Mattel",
                            Nome = "Boneca Barbie",
                            Quantidade = 15
                        },
                        new
                        {
                            Id = 6L,
                            Marca = "SanDisk",
                            Nome = "Pen Drive",
                            Quantidade = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
